"""Design sampling, immutable dataset artifacts, and sweep state."""

from soufflerie.datagen.design import (
    CANDIDATE_COUNT,
    DESIGN_SAMPLE_COUNT,
    DIMENSION_NAMES,
    SPLIT_SALT,
    DesignPoint,
    DesignSummary,
    DistributionSummary,
    UnsplitDesignPoint,
    assign_splits,
    case_config_for_point,
    generate_design_summary,
    render_design_summary,
    sample_design,
)
from soufflerie.datagen.run_artifact import (
    OUTPUT_SHAPE,
    RUN_MEMBER_ORDER,
    SOLVER_SHAPE,
    CuratedRunFields,
    LocalRunArtifactStore,
    QuantizationStatistic,
    RunArtifact,
    RunArtifactStore,
    RunMetadata,
    curate_solver_result,
    encode_run_fields,
    run_member_descriptors,
)
from soufflerie.datagen.schema_registry import rendered_datagen_schema_documents
from soufflerie.datagen.sweep_state import (
    LEASE_DURATION,
    LEASE_EXPIRED_CODE,
    MAX_SWEEP_ATTEMPTS,
    CaseState,
    LocalSweepStateStore,
    ResumePlan,
    SweepStateStore,
    VerifiedCaseRun,
    build_resume_plan,
)

__all__ = [
    "CANDIDATE_COUNT",
    "DESIGN_SAMPLE_COUNT",
    "DIMENSION_NAMES",
    "LEASE_DURATION",
    "LEASE_EXPIRED_CODE",
    "MAX_SWEEP_ATTEMPTS",
    "OUTPUT_SHAPE",
    "RUN_MEMBER_ORDER",
    "SOLVER_SHAPE",
    "SPLIT_SALT",
    "CaseState",
    "CuratedRunFields",
    "DesignPoint",
    "DesignSummary",
    "DistributionSummary",
    "LocalRunArtifactStore",
    "LocalSweepStateStore",
    "QuantizationStatistic",
    "ResumePlan",
    "RunArtifact",
    "RunArtifactStore",
    "RunMetadata",
    "SweepStateStore",
    "UnsplitDesignPoint",
    "VerifiedCaseRun",
    "assign_splits",
    "build_resume_plan",
    "case_config_for_point",
    "curate_solver_result",
    "encode_run_fields",
    "generate_design_summary",
    "render_design_summary",
    "rendered_datagen_schema_documents",
    "run_member_descriptors",
    "sample_design",
]
